### PR TITLE
Pass compatibility flag to v2

### LINKED ISSUE #15: Need to pass `--compatibility`-flag
When running without `--compatibility`-flag the new `docker compose` will use a hyphen for the hostname instead of an underscore. This breaks compatibility with old scripts. I believe the new flag was introduce for exactly solving such problems and  compose-switch should make use of it.

### PR DESCRIPTION
**Pull request by mat007**
Fixes #15

### CODE REVIEW

**Comment by ndeloof** [comment]
Too late, but a strong 👎  on this.
Many users (including me) use `docker-compose` as a command and expect a full V2 target. This should not just be considered a "legacy compatibility" mode

**Comment by mat007** [comment]
Ah sorry @ndeloof I should have pinged you when creating this PR.

Can you elaborate a bit? If you’re expecting V2, is there any reason you can’t directly invoke `docker compose`?

**Comment by ndeloof** [comment]
As of 2.0.1 compose v2 is distributed on a few Linux distros (typically: arch) as drop-in replacement for `docker-compose` 
I also have a bunch of scripts here relying on `docker-compose` but still wanted to use V2.

IMHO compose v2 should not be restricted to "cli plugin" and `docker space compose`, this is just the new compose.

**Comment by mat007** [comment]
But isn’t `docker-compose` usable as a standalone binary now?
Discussing with @ulyssessouza he mentioned that Arch Linux are actually using the plugin directly as a binary just like that?

**Comment by ndeloof** [comment]
Yes indeed, our released binary can be used both as a CLI plugin or standalone binary as drop in replacement for `docker-compose`. That's my point: using the latter I expect I can run compose V2 I installed, I'm not in a hidden transition phase

**Pull request merged**
